---
title: "Platyceros_Code"
output: html_document
date: "2025-03-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load required packages
library(tidyverse)
library(here)
library(ggplot2)
library(DHARMa)
library(glmmTMB)
library(cowplot)
library(car)
library(raster)
library(ncdf4)
library(tmap)
library(sf)
library(rstatix)
library(readxl) 
library(rnaturalearth)
library(ggspatial)
```
```{r}
#Read in raw prawn data 
raw_prawn <- read.csv(file = here("Bewick_Richards_DS2024_PrawnData.csv"))
```


```{r}
#Doing a data-control check of our measurements by adding abdominal and carapace 
#length to make sure they are approximately equal to total length and identify 
#outliers that fall outside of a 10mm buffer 
#The intercept and slopes for the grey lines are representing the 10mm buffer 
#as a visual to show which data points fall outside of it. 

raw_prawn$total_check <- raw_prawn$carapace_length.mm.+
  raw_prawn$abdominal_length.mm.
lm_total_check <- lm(total_check ~ total_length_raw..mm., data = raw_prawn)
summary(lm_total_check)
ggplot(raw_prawn, aes(x=total_length_raw..mm., y=total_check))+
  geom_point() +
  geom_abline(intercept=6.63670, slope=0.95506, color="blue") +
  geom_abline(intercept=16.63670, slope=0.95506, color="grey") +
 geom_abline(intercept=-4.63670, slope=0.95506, color="grey") +
  theme_classic()+
  labs(x="Total Length Measured(mm)", y="Carapace + Abdomen Length(mm)")

#One outlier was identified, which was fixed using ImageJ and the data was 
#re-loaded with a total_length_raw column (original data) and a total_length 
#column which is the corrected data used for the rest of the analyses 
```
```{r}
#Creating a new column with a ratio of abdomen length : carapace length
ac_ratio_prawn<-raw_prawn%>%
  mutate(abdomen_carapace_ratio = abdominal_length.mm./carapace_length.mm.)

summarize(ac_ratio_prawn)
```
```{r}
#Now we are comparing the ratio for our two sites, Wizard and Weld. 
site_compare <- ggplot(data=ac_ratio_prawn,(aes(x=total_length.mm.,
                      abdomen_carapace_ratio,color=site))) +
  geom_point() +
  geom_smooth(method=lm) +
  labs(x="Total Length (mm)", y="Abdomen / Carapace Ratio") +
  theme_classic()
site_compare

#Saving this figure to use in our paper 
ggsave("Paper_figures/Figure_5.png", plot = site_compare,
       width = 10, height = 6, dpi = 300)

```
## **Egg volume analyses**
```{r}
#Omiting the na's from the egg data
clean_egg<-raw_prawn%>%
  filter(egg.volume..mm.3.!="na")

#The egg volume column was defined as characters, so here we are changing 
#it to numeric.
clean_egg$egg.volume..mm.3. <- 
  as.numeric(as.character(clean_egg$egg.volume..mm.3.))

#Plotting egg volume, first a histogram to look at the distribution of the data
ggplot(data=clean_egg,(aes(x=egg.volume..mm.3.))) +
  geom_histogram() +
  theme_classic()

#Now let's see what a scatter plot will show
ggplot(data=clean_egg,(aes(x=total_length.mm.,egg.volume..mm.3.))) +
  geom_point() +
  geom_smooth(color="steelblue",method=lm) +
  labs(x="Total Length (mm)",y="Egg Volume (mm3)") +
  theme_classic()
```


##**Linear Models to Determine Allometry/Isometry**
```{r}
#Running shapiro tests to determine if each of our log-transformed variables are 
#normally distributed across both sites, to see it linear models might work  
shapiro.test(raw_prawn$log_t_length)
qqnorm(raw_prawn$log_t_length) 
qqline(raw_prawn$log_t_length)
hist(raw_prawn$log_t_length)
#Making qqplots and histograms to look at the data and visually assess normality. 

shapiro.test(raw_prawn$log_carapace)
qqnorm(raw_prawn$log_carapace) 
qqline(raw_prawn$log_carapace)
hist(raw_prawn$log_carapace)

shapiro.test(raw_prawn$log_abdomen)
qqnorm(raw_prawn$log_abdomen) 
qqline(raw_prawn$log_abdomen)
hist(raw_prawn$log_abdomen)

shapiro.test(clean_egg$log_volume)
qqnorm(clean_egg$log_abdomen) 
qqline(clean_egg$log_abdomen)
hist(clean_egg$log_abdomen)
#All of these variables have p-value >0.05, so are normally distributed across 
#all of our data 
```

```{r}
#Making linear models for our log transformed data 

#Linear model for carapace and total length
lm_c_t= lm (log_carapace~log_t_length, data = raw_prawn) 
plot(lm_c_t)
plot(simulateResiduals(lm_c_t))
#Residuals are not normal according to the DHARMa package, but there are no glm 
#options that work well for this data and let us graph it (the only glms that 
#fit transform the data and make it not comparable to the isometry line). The 
#DHARMa package is very sensitive and the the data sufficiently fit the model 
#assumptions based on visual assessment, therefore we will use this linear model. 
summary(lm_c_t)
cl95<-confint(lm_c_t)
cl95
#This gives us the summary (slope and intercept) and 95% confidence intervals for 
#this model 

#Linear model for abdomen and total length
lm_a_t= lm (log_abdomen~log_t_length, data = raw_prawn) 
plot(simulateResiduals(lm_a_t))
#Residuals are not normal so we try a glm

glm_a_t <-glmmTMB(log_abdomen~log_t_length, data=raw_prawn,
                  family=t_family())
plot(simulateResiduals(glm_a_t))
#Using the glm family t_family, the model has residuals that are normal 
summary(glm_a_t)
cl95<-confint(glm_a_t)
cl95
#This gives us the 95% confidence intervals from our glm and the summary 


#Linear model for carapace and abdomen
lm_c_a= lm (log_carapace~log_abdomen, data = raw_prawn) 
summary.lm (lm_c_a)
#This gives us the 95% confidence intervals from our linear model
cl95<-confint(lm_c_a) 
cl95
plot(simulateResiduals(lm_c_a))
#Residuals are normal so the assumptions for the lm are met 

#Linear model for egg volume and total length
lm_v_t= lm (log_volume~log_t_length, data = clean_egg) 
summary.lm (lm_v_t)
#This gives us the 95% confidence intervals from our linear model
cl95<-confint(lm_v_t) 
cl95
plot(simulateResiduals(lm_v_t))
#Residuals are normal so the assumptions for the lm are met 
```

```{r}
#Plot out the predicted (isometry line) versus the CI and glm/lm slopes
# Red = isometry lines, colours = lm/glm slopes, grey = CI of linear models 
#isometry line and confidence interval intercepts are set to match the model 
#line intercept for accurate comparison. Scale is set to best visualize our 
#data points as well as the line of isometry, the model, and both confidence 
#interval lines. 

#Plotting carapace vs total length
plot_c_t <- ggplot(raw_prawn, (aes(x=log_t_length, y=log_carapace))) + 
  geom_point() +
  geom_abline(intercept=-1.45070,slope=1, colour="red",linewidth=0.8) + 
  geom_abline(intercept=-1.45070,slope=1.04650, colour="green",linewidth=0.8) +
  geom_abline(intercept=-1.45070, slope=1.007174, colour="grey")+
  geom_abline (intercept=-1.45070, slope=1.085835, colour="grey") +
  scale_x_continuous(expand = c(0, 0), limits = c(4, 5.5)) +
  scale_y_continuous(expand = c(0, 0), limits = c(2.5, 4)) +
  xlab("Ln(total length)") +
  ylab("Ln(carapace length)") +
  theme_classic()
  plot_c_t
  
#Plotting abdomen vs total length
plot_a_t <- ggplot(raw_prawn, (aes(x=log_t_length, y=log_abdomen))) + 
  geom_point() +
  geom_abline(intercept=-0.07982,slope=1, colour="red",linewidth=0.8) + 
  geom_abline(intercept=-0.07982,slope=0.94725, colour="blue",linewidth=0.8) +
  geom_abline(intercept=-0.07982,slope=0.9199612, colour="grey")+
  geom_abline (intercept=-0.07982,slope=0.97453519, colour="grey") +
  scale_x_continuous(expand = c(0, 0), limits = c(4.25, 5.25)) +
  scale_y_continuous(expand = c(0, 0), limits = c(3.75, 5)) +
  xlab("Ln(total length)") +
  ylab("Ln(abdomen length)") +
  theme_classic()
  plot_a_t
  
#Plotting carapace vs abdomen 
plot_c_a <- ggplot(raw_prawn, (aes(x=log_abdomen, y=log_carapace))) + 
  geom_point() +
  geom_abline(intercept=-1.48653,slope=1, colour="red",linewidth=0.8) + 
  geom_abline(intercept=-1.48653,slope=1.13218, colour="purple",linewidth=0.8) +
  geom_abline(intercept=-1.48653, slope=1.083341, colour="grey")+
  geom_abline (intercept=-1.48653, slope=1.181016, colour="grey") +
  scale_x_continuous(expand = c(0, 0), limits = c(3.5, 5.5)) +
  scale_y_continuous(expand = c(0, 0), limits = c(2.5, 4.5)) +
  xlab("Ln(abdomen length)") +
  ylab("Ln(carapace length)") +
  theme_classic()
  plot_c_a
  
#Plotting egg volume vs total length 
plot_v_t <- ggplot(clean_egg, (aes(x=log_t_length, y=log_volume))) + 
  geom_point() +
  geom_abline(intercept=-5.1187,slope=3, colour="red",linewidth=0.8) + 
  geom_abline(intercept=-5.1187,slope=2.8741, colour="yellow",linewidth=0.8) +
  geom_abline(intercept=-5.1187, slope=1.420228, colour="grey")+
  geom_abline (intercept=-5.1187, slope=4.327971, colour="grey") +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 15)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 15)) +
  xlab("Ln(total length)") +
  ylab("Ln(egg volume)") +
  theme_classic()
  plot_v_t

#Combining these 4 plots into one multi-panel plot  
multi_panel <-plot_grid(plot_c_t, plot_a_t, plot_c_a, plot_v_t,
        labels=c('A','B','C','D'),
    label_x=0.15)
multi_panel

#Saving this figure to be used in our paper 
ggsave("Paper_figures/Figure_3.png", plot = multi_panel, width = 10, height = 6, dpi = 300)
```

##**Comparing Sizes Between Wizard and Weld**

```{r}
#Finding the mean and SE for total length between the two sites 
raw_prawn %>%
group_by(site) %>%
summarize(mean = mean(total_length.mm.),
se = sd(total_length.mm.)/sqrt(length(total_length.mm.)))

#Finding the mean and SE for weight between the two sites 
raw_prawn %>%
group_by(site) %>%
summarize(mean = mean(weight.g.),
se = sd(weight.g.)/sqrt(length(weight.g.)))
```

```{r}
#Running Shapiro-Wilk and Bartlett tests for total length and total weight by 
#site, to check normality for t-tests between of these variables between sites 
raw_prawn %>%
  group_by(site) %>%
  shapiro_test(total_length.mm.)
#P-values are both > 0.05, so the total length is normally distributed at both 
#sites 

bartlett.test(total_length.mm. ~ site, data=raw_prawn)
#P-value > 0.05, so the variances are homoscedastic and this data can be used 
#in a t-test 

#t-test of total length between the two sites, weld and wizard.
tt_total_length <- t.test(total_length.mm. ~ site, data = raw_prawn, 
                          var.equal = T)
tt_total_length
#t = 4.3528, df = 90, p-value = 3.545e-05 (significant difference)

#Shapiro test for weight 
raw_prawn %>%
  group_by(site) %>%
  shapiro_test(weight.g.)
#P-value < 0.05 for both sites, so the weight data is not normally distributed 
#at either site. Thus we cannot do a t-test and try a glm instead 

#glm for weight between the two sites 
glm_weight <-glmmTMB(weight.g.~ site, data=raw_prawn,
                  family=lognormal())

plot(simulateResiduals(glm_weight))
summary(glm_weight)
#Residuals are normal and lognormal family works 
#p-value < 0.05, so there is a significant difference in weight between the 
#two sites 
```


```{r}
#Making a boxplot to compare total length by site 
site_t.length <- ggplot(raw_prawn,aes(x=site,y=total_length.mm., fill=site)) +
  geom_boxplot() +
  labs(x="Site", y="Total Length (mm)") +
  theme_classic()
site_t.length

#Making a boxplot to compare weight by site 
site_weight <- ggplot(raw_prawn, aes(x=site, y=weight.g., fill=site))+
  geom_boxplot() +
  labs(x="Site",y="Weight (g)") +
  theme_classic()
site_weight

#Combining the weight and total length boxplots into one figure 
Site_hist <-plot_grid(site_t.length, site_weight, 
        labels=c('A','B'),
    label_x=0.15)
Site_hist

#Saving this figure to use in our paper 
ggsave("Paper_figures/Figure_4.png", plot = Site_hist, 
       width = 10, height = 6, dpi = 300)

```

## **Site map and tidal flow quantification**

```{r spatial points, fig.width=4, fig.height=4}
#Making a map of our study sites 
#Creating a Vancouver island base map from Hakai shapefiles 
VI_baselayer <- read_sf(dsn = here::here("hakai_shapefiles", ""), 
                        stringsAsFactors = F)
VI_baselayer_sf <- st_as_sf(VI_baselayer)
ggplot(VI_baselayer_sf) +
  geom_sf() 

#Reading in prawn site info 
PrawnSites <- read_excel(here::here("Bewick_Richards_DS2024_SiteData.xlsx"))

#Plotting our study site data points by geographic location 
points_plot <- ggplot(PrawnSites, (aes(x=Long, y=Lat))) +
  geom_point() +
  xlab("Longitude (°W)") +
  ylab("Latitude (°N)")+
  theme_classic()
points_plot

st_crs(VI_baselayer_sf) <- "+proj=longlat +datum=WGS84 +no_defs"

#Setting the bounds of our map based on where are study sites are, with a buffer
lat_min = min(PrawnSites$Lat) - 0.03
lat_max = max(PrawnSites$Lat) + 0.03
long_min = min(PrawnSites$Long) - 0.07
long_max = max(PrawnSites$Long) + 0.07

#Making a basic map with our study sites
ggplot() +
  geom_sf(data = VI_baselayer_sf) +
  coord_sf(xlim = c(long_min, long_max),
           ylim = c(lat_min, lat_max)) +
  geom_point(data = PrawnSites, mapping = aes(x = Long, y = Lat), color = "red") 
```



```{r pretty base map with points, fig.width=15, fig.height=7}
#Making a pretty theme for our site map 
theme.dgm.map <- function (){
  theme_bw(base_size = 12) +
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12, face = "plain"),
    legend.text = element_text(size = 10, face = "plain"),
    legend.title = element_text(size = 14, face = "bold")) 
}

#Making our site map, with labels and a compass 
(L08_Map <- ggplot() +
    geom_sf(data = VI_baselayer_sf, color = "black", fill = "lightgrey") +
  coord_sf(xlim = c(long_min, long_max),
           ylim = c(lat_min, lat_max)) +
  geom_point(data = PrawnSites, mapping = aes(x = Long, y = Lat),
             size = 4) + 
  geom_point(data = PrawnSites, mapping = aes(x = Long, y = Lat),
             shape = 1, size = 4,colour = "black")+
  labs(x = " \nLongitude", y = "Latitude\n ") +
 theme.dgm.map() +
    scale_x_continuous(breaks = c(-125.04, -125.1,-125.16,-125.22)) +
scale_y_continuous(breaks = c(48.85, 48.90,48.95)) +
  annotation_north_arrow(
   location = "tr",
  which_north = "true",
  style = north_arrow_fancy_orienteering
  ) +
  annotation_scale(location = "br")+
  geom_label(data = PrawnSites, 
             mapping = aes(x = -125.163, y = 48.8621527, 
                           label = "Wizard")) +
  geom_label(data=PrawnSites,
             mapping = aes (x=-125.095, y=48.9630364, label="Weld")))

#Making a Vancouver Island inset to show our relative location 
(VI_Inset <- ggplot(VI_baselayer_sf) +
  geom_sf() +
  coord_sf(ylim = c(48, 52), xlim = c(-129, -122)) +
  theme.dgm.map() +
  geom_rect(xmin = long_min, xmax = long_max, ymin = lat_min, 
        ymax = lat_max,
            color = "red", fill = NA) +
  theme(axis.text = element_text(size = 8)) +
  scale_x_continuous(breaks = c(-128, -125, -122)) +
  scale_y_continuous(breaks = c(48, 50, 52)))

#Putting the inset onto the site map 
(map_w_inset <- ggdraw(L08_Map) +
  draw_plot(VI_Inset, x = 0.3, y = 0.65, width = 0.3, height = 0.3))

```

```{r save map, fig.width=15, fig.height=7}
#Saving this map to use in our paper 
png(filename = here("Paper_figures", "Figure_1.png"), width = 15, height = 7, 
    units = "in", pointsize = 15, res = 600)

(map_w_inset <- ggdraw(L08_Map) +
 draw_plot(VI_Inset, x = 0.3, y = 0.65, width = 0.3, height = 0.3))

dev.off()
```

```{r}
#Quantifying our two sites by monthly horizontal water movement using Copernicus 
#satellite data.
horizontal_currents <- brick(here("horizontal_monthly.nc"))

horizontal_currents <- calc(horizontal_currents,fun=mean)

crs(horizontal_currents) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

tm_shape(horizontal_currents) +
  tm_raster()

prawn_coords_raw <- data.frame(site_name = c("Weld","Wizard"),
                        long = c(-125.096361,-125.162997),
                        lat = c(48.955586,48.855278)
)

#Make an sf-object out of them
prawn_coords<- st_as_sf( prawn_coords_raw, coords = c( "long", "lat" ) )

prawn_coords_raw$eastward_velocity <- raster::extract(
  horizontal_currents, prawn_coords, fun = mean, na.rm = TRUE)
#We used the eastward velocity (m/s) from the prawn_cords_raw. 
#Wizard had higher tidal flow (0.036m/s WEST) compared to 
#Weld (0.025m/s WEST)
```

```{r}
##for the github token, use the PAT as your password when pushing. make sure 
#hit scope and workflow 
```


















